### ISSUE TITLE
[Bug] hata.ext.patchouli can drop IndexError

### ISSUE THREAD

**Issue by HuyaneMatsu** [HuyaneMatsu/hata#81]
### Description

Unexpected `IndexError` when trying to serialize.

### Reproduction Steps

Try to serialize `.../hata/ext/solarlink/filters/Equalizer`.

### Expected behaviour

No exception occurs.

### Actual behaviour

```py3
Traceback (most recent call last):
  File ".../hata/ext/patchouli/module_mapper.py", line 497, in html_extended_with_structure
    html_extended, html_extended_structure = html_serialize_docs_extended(self, True, True)
  File ".../hata/ext/patchouli/builder_html_extended.py", line 1891, in html_serialize_docs_extended
    structure = serializer.structurize()
  File ".../hata/ext/patchouli/builder_html_extended.py", line 1574, in structurize
    child = section.structurize()
  File ".../hata/ext/patchouli/builder_html_extended.py", line 772, in structurize
    serializer = serializer_type(unit, path / name)
  File ".../hata/ext/patchouli/builder_html_extended.py", line 551, in __init__
    parameter_section = ParameterSection(section_content, object_, path)
  File ".../hata/ext/patchouli/builder_html_extended.py", line 1259, in __init__
    self.extend(section_content)
  File ".../hata/ext/patchouli/builder_html_extended.py", line 1289, in extend
    self.parameter_sub_sections.append(ParameterSubSection(header, section_content))
  File ".../hata/ext/patchouli/builder_html_extended.py", line 1028, in __init__
    parameter_name_part = header_contents[0]
IndexError: list index out of range
```

### System information

Hata version: 1.3.4
Scarletio version: 1.0.34
Platform: Linux-5.13.0-1022-aws-x86_64-with-glibc2.2.5
Python implementation: cpython
Python version: 3.8 final

**Comment by HuyaneMatsu** [comment]
Fixed. Will be alive next update 👌🏻
